from .Proto import Proto
"""The Robot node is a generic type of robot. parent: Solid"""
class ROBOT(Proto):
    ...
"""The Background node defines the background used for rendering the 3D world."""
class BACKGROUND(Proto):
    ...
"""A Billboard node contains children nodes that rotate and translate automatically to face the viewpoint. It is otherwise similar to a Group node. parent: Group"""
class BillBoarad(Proto):
    ...
"""The CadShape node defines a geometry and appearance from a '.dae' or '.obj' file."""
class CadShape(Proto):
    ...
"""The Charger node is used to model a special kind of battery charger for the robots. When a robot gets close to a Charger, the robot's battery gets recharged. parent: Solid"""
class Charger(Proto):
    ...
"""The DirectionalLight node defines a light source that illuminates along rays parallel to a given 3-dimensional vector. A DirectionalLight node is well-suited to model sunlight, for example. If you want to model a light bulb you should rather use a PointLight or a SpotLight node."""
class DIRECIONALLIGHT(Proto):
    ...
"""A Fluid node can be used to represent a collection of fluid volumes where hydrostatic and hydrodynamic forces apply. parent: Pose"""
class FLUID(Proto):
    ...
"""The Fog node provides a way to simulate atmospheric effects by blending objects with the color specified by the color field based on the distances of the various objects from the camera."""
class FOG(Proto):
    ...
"""A Group node contains children nodes without introducing a new transformation. It is equivalent to a Transform node without the "translation" and "rotation" fields."""
class GROUP(Proto):
    ...
"""The PointLight node specifies a light source that emits light equally in all directions. The emitted light can be detected by a LightSensor node. Putting a PointLight onboard a robot allows the PointLight to move with the robot."""
class POINTLIGHT(Proto):
    ...
"""The Pose node is a grouping node that defines a coordinate system for its children that is relative to the coordinate system of its parent. parent: Group"""
class POSE(Proto):
    ...
"""A Shape node is a visual objects that includes both an 'appearance' and a 'geometry'. A Shape can also be used in a 'boundingObject', in this case, only its 'geometry' field is taken into account."""
class SHAPE(Proto):
    ...
"""A Solid node can be used to represent objects in the simulated environment (e.g. obstacles, walls, ground, robot parts, etc.). Solid nodes can be collision detected (boundingObject) and therefore can prevent objects from intersecting. In addition, Solid nodes can have an optional Physics node that allow them to be simulated with the physics engine. parent: Pose"""
class SOLID(Proto):
    ...
"""The SpotLight node defines a light source that emits light from a specific point along a specific direction vector and constrained within a specific angle. The light emitted by a SpotLight (or other light sources) can be detected by a LightSensor node."""
class SPOTLIGHT(Proto):
    ...
"""The Transform node is a grouping node that defines a coordinate system for its children that is relative to the coordinate system of its parent. The 'scale' field of a Transform node can be adjusted only in a graphical context and not in a 'boundingObject' context. parent: Pose"""
class TRANSFORM(Proto):
    ...
"""This is a class to control the veiw point"""
class VIEWPOINT(Proto):
    ...
"""This is a class to control the World info"""
class WORLDINFO(Proto):
    ...
